name: brewmate_coffee
description: Aplikasi pembuat kopi profesional
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ================== CORE ==================
  http: ^1.2.0
  intl: ^0.19.0
  provider: ^6.1.2

  # ================== STORAGE & UTIL ==================
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  share_plus: ^10.0.2

  # ================== LOCATION & PERMISSION ==================
  geolocator: ^13.0.1
  permission_handler: ^11.3.1

  # ================== FIREBASE (STABIL & KOMPATIBEL) ==================
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # ================== UI ==================
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/logo.png
  remove_alpha_ios: true
